# Generated by Django 5.2.4 on 2025-07-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="code",
            field=models.CharField(max_length=10, verbose_name="code"),
        ),
    ]
