# Generated by Django 5.2.4 on 2025-07-29 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0002_alter_commodity_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="date"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=5, max_digits=20, verbose_name="price"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="commodities.commodity",
                        verbose_name="commodity",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="The unit of this price.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commodities.commodity",
                        verbose_name="unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "price",
                "verbose_name_plural": "prices",
                "ordering": ["-date"],
            },
        ),
    ]
