# Generated by Django 5.2.4 on 2025-07-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0003_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={
                "get_latest_by": "date",
                "ordering": ["-date"],
                "verbose_name": "price",
                "verbose_name_plural": "prices",
            },
        ),
    ]
