# Generated by Django 5.2.4 on 2025-07-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0004_alter_price_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="auto_update",
            field=models.BooleanField(default=False, verbose_name="auto update"),
        ),
        migrations.AddField(
            model_name="commodity",
            name="backend",
            field=models.CharField(
                blank=True,
                choices=[("yahoo", "Yahoo Finance"), ("custom", "Custom")],
                default="yahoo",
                max_length=10,
                null=True,
                verbose_name="backend",
            ),
        ),
        migrations.AddField(
            model_name="commodity",
            name="commodity_type",
            field=models.CharField(
                choices=[
                    ("currency", "Currency"),
                    ("stock", "Stock"),
                    ("fund", "Fund"),
                    ("warrant", "Warrant"),
                    ("asset", "Asset"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=10,
                verbose_name="commodity type",
            ),
        ),
        migrations.AddField(
            model_name="commodity",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="website"),
        ),
        migrations.AddField(
            model_name="commodity",
            name="xpath_selector",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="xpath selector"),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="code",
            field=models.CharField(max_length=10, unique=True, verbose_name="code"),
        ),
        migrations.AddConstraint(
            model_name="commodity",
            constraint=models.UniqueConstraint(fields=("name", "code"), name="unique_commodity"),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.UniqueConstraint(fields=("commodity", "unit", "date"), name="unique_price_per_day"),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(condition=models.Q(("price__gt", 0)), name="positive_price"),
        ),
    ]
