# Generated by Django 5.2.4 on 2025-07-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0005_commodity_auto_update_commodity_backend_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="backend",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="backend"),
        ),
    ]
