# Generated by Django 5.2.4 on 2025-07-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0006_price_backend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="backend",
            field=models.CharField(default="Manual", max_length=250, verbose_name="backend"),
        ),
    ]
