# Generated by Django 5.2.4 on 2025-07-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0008_remove_price_unique_price_per_day_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="price",
            name="unique_price_per_day",
        ),
    ]
