# Generated by Django 5.2.4 on 2025-07-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0009_remove_price_unique_price_per_day"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="price",
            constraint=models.UniqueConstraint(
                fields=("commodity", "unit", "date", "backend"),
                name="unique_price_per_day",
            ),
        ),
    ]
