# Generated by Django 5.2.4 on 2025-08-01 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0010_price_unique_price_per_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commodity",
            name="xpath_selector",
        ),
        migrations.AddField(
            model_name="commodity",
            name="website_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="commodities.commodity",
                verbose_name="website currency",
            ),
        ),
        migrations.AddField(
            model_name="commodity",
            name="xpath_selector_amount",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="xpath selector amount",
            ),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="backend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yahoo", "Yahoo Finance"),
                    ("website", "Website Scraper"),
                    ("custom", "Custom"),
                ],
                default="yahoo",
                max_length=10,
                null=True,
                verbose_name="backend",
            ),
        ),
    ]
