# Generated by Django 5.2.5 on 2025-08-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0011_remove_commodity_xpath_selector_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="commodity",
            name="unique_commodity",
        ),
    ]
