# Generated by Django 5.2.5 on 2025-08-09 20:37

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0012_remove_commodity_unique_commodity"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="commodity",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                name="uniq_commodity_code_ci",
            ),
        ),
    ]
