# Generated by Django 5.2.4 on 2025-08-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[
                    ("assets", "Assets"),
                    ("liabilities", "Liabilities"),
                    ("expenses", "Expenses"),
                    ("income", "Income"),
                    ("equity", "Equity"),
                    ("cash", "Cash"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=15,
                verbose_name="type",
            ),
        ),
    ]
