# Generated by Django 5.2.4 on 2025-08-03 21:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0011_remove_commodity_xpath_selector_and_more"),
        ("ledger", "0003_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="ledger.bank",
                verbose_name="bank",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="default_currency",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"commodity_type": "currency"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="commodities.commodity",
                verbose_name="default currency",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
    ]
