# Generated by Django 5.2.4 on 2025-08-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0004_account_bank_account_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="calculated_name",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=1000,
                verbose_name="calculated name",
            ),
        ),
    ]
