# Generated by Django 5.2.4 on 2025-08-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0005_account_calculated_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": ["name"],
                "verbose_name": "account",
                "verbose_name_plural": "accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="bank",
            options={
                "ordering": ["name"],
                "verbose_name": "bank",
                "verbose_name_plural": "banks",
            },
        ),
    ]
