# Generated by Django 5.2.4 on 2025-08-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0006_alter_account_options_alter_bank_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(db_index=True, max_length=250, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="bank",
            name="name",
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name="name"),
        ),
    ]
