# Generated by Django 5.2.4 on 2025-08-06 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0008_transaction_remove_account_calculated_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postings",
                        to="ledger.account",
                        verbose_name="account",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postings",
                        to="ledger.transaction",
                        verbose_name="transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "posting",
                "verbose_name_plural": "postings",
                "ordering": ["transaction", "account"],
            },
        ),
    ]
