# Generated by Django 5.2.4 on 2025-08-06 20:22

import django.db.models.deletion
from django.db import migrations, models

import ledger.models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0011_remove_commodity_xpath_selector_and_more"),
        ("ledger", "0009_posting"),
    ]

    operations = [
        migrations.AddField(
            model_name="posting",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="amount"
            ),
        ),
        migrations.AddField(
            model_name="posting",
            name="commodity",
            field=models.ForeignKey(
                default=ledger.models._get_base_currency,
                on_delete=django.db.models.deletion.PROTECT,
                to="commodities.commodity",
                verbose_name="commodity",
            ),
        ),
    ]
