# Generated by Django 5.2.4 on 2025-08-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0010_posting_amount_posting_commodity"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="amounts",
            field=models.JSONField(default=dict, verbose_name="amounts"),
        ),
    ]
