# Generated by Django 5.2.5 on 2025-08-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0011_transaction_amounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amounts",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="amounts"),
        ),
    ]
