# Generated by Django 5.2.5 on 2025-08-07 20:06

import django.db.models.deletion
from django.db import migrations, models

import ledger.models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0011_remove_commodity_xpath_selector_and_more"),
        ("ledger", "0012_alter_transaction_amounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="default_currency",
            field=models.ForeignKey(
                blank=True,
                default=ledger.models._get_base_currency,
                limit_choices_to={"commodity_type": "currency"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="commodities.commodity",
                verbose_name="default currency",
            ),
        ),
    ]
