# Generated by Django 5.2.5 on 2025-08-07 20:11

import django.db.models.deletion
from django.db import migrations, models

import ledger.models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0011_remove_commodity_xpath_selector_and_more"),
        ("ledger", "0013_alter_account_default_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="posting",
            name="foreign_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="foreign amount",
            ),
        ),
        migrations.AddField(
            model_name="posting",
            name="foreign_commodity",
            field=models.ForeignKey(
                blank=True,
                default=ledger.models._get_base_currency,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="foreign_postings",
                to="commodities.commodity",
                verbose_name="foreign commodity",
            ),
        ),
        migrations.AlterField(
            model_name="posting",
            name="commodity",
            field=models.ForeignKey(
                default=ledger.models._get_base_currency,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="postings",
                to="commodities.commodity",
                verbose_name="commodity",
            ),
        ),
    ]
