# Generated by Django 5.2.5 on 2025-08-07 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0011_remove_commodity_xpath_selector_and_more"),
        ("ledger", "0014_posting_foreign_amount_posting_foreign_commodity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posting",
            name="foreign_amount",
        ),
        migrations.RemoveField(
            model_name="posting",
            name="foreign_commodity",
        ),
        migrations.AddField(
            model_name="posting",
            name="converted_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="converted amount",
            ),
        ),
        migrations.AddField(
            model_name="posting",
            name="converted_commodity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="converted_postings",
                to="commodities.commodity",
                verbose_name="converted commodity",
            ),
        ),
        migrations.AddField(
            model_name="posting",
            name="is_balance_posting",
            field=models.BooleanField(default=False, verbose_name="is balance posting"),
        ),
    ]
