# Generated by Django 5.2.5 on 2025-08-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0015_remove_posting_foreign_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posting",
            options={},
        ),
        migrations.RemoveField(
            model_name="posting",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="posting",
            name="commodity",
        ),
        migrations.RemoveField(
            model_name="posting",
            name="converted_amount",
        ),
        migrations.RemoveField(
            model_name="posting",
            name="converted_commodity",
        ),
        migrations.RemoveField(
            model_name="posting",
            name="created",
        ),
        migrations.RemoveField(
            model_name="posting",
            name="is_balance_posting",
        ),
        migrations.RemoveField(
            model_name="posting",
            name="updated",
        ),
    ]
