# Generated by Django 5.2.5 on 2025-08-07 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0016_alter_posting_options_remove_posting_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posting",
            options={
                "ordering": ["transaction", "account"],
                "verbose_name": "posting",
                "verbose_name_plural": "postings",
            },
        ),
        migrations.AddField(
            model_name="posting",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="posting",
            name="is_balance_posting",
            field=models.BooleanField(default=False, verbose_name="is balance posting"),
        ),
        migrations.AddField(
            model_name="posting",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
    ]
