# Generated by Django 5.2.5 on 2025-08-07 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0011_remove_commodity_xpath_selector_and_more"),
        ("ledger", "0018_posting_amount_posting_commodity"),
    ]

    operations = [
        migrations.AddField(
            model_name="posting",
            name="foreign_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="foreign amount",
            ),
        ),
        migrations.AddField(
            model_name="posting",
            name="foreign_commodity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="foreign_postings",
                to="commodities.commodity",
                verbose_name="foreign commodity",
            ),
        ),
    ]
