# Generated by Django 5.2.5 on 2025-08-08 12:40

import django.db.models.deletion
from django.db import migrations, models

import ledger.models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0011_remove_commodity_xpath_selector_and_more"),
        ("ledger", "0019_posting_foreign_amount_posting_foreign_commodity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="default_currency",
            field=models.ForeignKey(
                default=ledger.models._get_base_currency,
                limit_choices_to={"commodity_type": "currency"},
                on_delete=django.db.models.deletion.PROTECT,
                to="commodities.commodity",
                verbose_name="default currency",
            ),
        ),
    ]
