# Generated by Django 5.2.5 on 2025-08-09 20:14

import django.db.models.deletion
from django.db import migrations, models

import ledger.models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0011_remove_commodity_xpath_selector_and_more"),
        ("ledger", "0022_alter_posting_foreign_commodity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posting",
            name="foreign_commodity",
            field=models.ForeignKey(
                blank=True,
                default=ledger.models._get_base_currency,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="foreign_postings",
                to="commodities.commodity",
                verbose_name="foreign commodity",
            ),
        ),
    ]
